# Generated by Django 3.2 on 2021-04-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_article_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
