# Generated by Django 3.2 on 2021-04-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_auto_20210427_0233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='article',
            name='guid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='guid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
