# Generated by Django 3.2 on 2021-05-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_auto_20210427_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('order',), 'verbose_name': 'Question'},
        ),
    ]
