# Generated by Django 3.2 on 2021-04-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('proposal_id', models.CharField(max_length=64, null=True)),
                ('proposal_exists', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('account_id', models.CharField(blank=True, max_length=64, null=True)),
                ('email_valid', models.BooleanField(default=False)),
                ('contact_id', models.CharField(blank=True, max_length=64, null=True)),
                ('contact_created', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('client_ip', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.session')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
