# Generated by Django 3.2 on 2021-05-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='client_ip',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
