# Generated by Django 3.2 on 2021-10-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_error',
        ),
        migrations.AddField(
            model_name='session',
            name='with_error',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=64),
        ),
    ]
