# Generated by Django 3.2 on 2021-10-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticresource',
            name='salesforce_category',
            field=models.CharField(choices=[('Show_Case_Study__c', 'Show Case Study'), ('Show_Quick_Start_Guide__c', 'Show Quick Start Guide'), ('Show_Brochure__c', 'Show Brochure'), ('Show_Kiwapower_at_a_Glance_video__c', 'Show Kiwapower at a Glance video')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='staticresource',
            unique_together={('is_active', 'salesforce_category')},
        ),
    ]
