# Generated by Django 3.2 on 2021-05-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_alter_session_client_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='client_geolocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
