# Generated by Django 3.2 on 2021-05-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_session_client_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='device',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
