# Generated by Django 3.2 on 2021-11-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_auto_20211020_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticresource',
            name='document_en',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='staticresource',
            name='document_es',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
