# Generated by Django 3.2 on 2021-12-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_auto_20211127_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesforcecategory',
            options={'verbose_name_plural': 'WEB Proposal files'},
        ),
    ]
