# Generated by Django 3.2 on 2021-12-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_alter_salesforcecategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesforcecategory',
            options={'verbose_name': 'Web Proposal field', 'verbose_name_plural': 'Web Proposal fields'},
        ),
        migrations.RenameField(
            model_name='staticresource',
            old_name='salesforce_category',
            new_name='web_proposal_field',
        ),
        migrations.AlterUniqueTogether(
            name='staticresource',
            unique_together={('is_active', 'web_proposal_field')},
        ),
    ]
