# Generated by Django 3.2 on 2021-05-27 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_alter_sessionevent_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('api_call_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sf_object', models.CharField(blank=True, max_length=255, null=True)),
                ('sf_error', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='proposal.session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
