# Generated by Django 3.2 on 2022-04-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("proposal", "0006_auto_20211203_1058")]
    operations = [
        migrations.AddField(
            model_name="errorlog", name="data", field=models.JSONField(default=dict, verbose_name="Request data")
        )
    ]
