# Generated by Django 3.2 on 2021-09-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file_description', models.CharField(blank=True, max_length=255, null=True)),
                ('file_description_es', models.CharField(blank=True, max_length=255, null=True)),
                ('file_description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('s3_file_location', models.TextField()),
                ('salesforce_file_id', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='sf_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
