# Generated by Django 3.2 on 2021-12-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_auto_20211203_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticresource',
            name='s3_file_location_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticresource',
            name='s3_file_location_es',
            field=models.TextField(blank=True, null=True),
        ),
    ]
