# Generated by Django 3.2 on 2021-09-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0007_auto_20210929_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticresources',
            name='salesforce_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staticresources',
            name='file_description',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staticresources',
            name='file_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staticresources',
            name='file_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staticresources',
            name='s3_file_location',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='staticresources',
            name='salesforce_file_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
