# Generated by Django 3.2 on 2021-09-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0008_auto_20210929_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticresources',
            name='salesforce_category',
            field=models.CharField(max_length=50),
        ),
    ]
