# Generated by Django 3.2 on 2021-09-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0009_alter_staticresources_salesforce_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticresources',
            name='file_extension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staticresources',
            name='s3_file_location',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staticresources',
            name='salesforce_category',
            field=models.CharField(choices=[('Show_Case_Study__c', 'Show Case Study'), ('Show_Quick_Start_Guide__c', 'Show Quick Start Guide'), ('Show_Brochure__c', 'Show Brochure'), ('Show_Kiwapower_at_a_Glance_video__c', 'Show Kiwapower at a Glance video')], max_length=50),
        ),
    ]
