# Generated by Django 3.2 on 2021-09-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0010_auto_20210930_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticresources',
            name='salesforce_category',
            field=models.CharField(choices=[('Show_Case_Study__c', 'Show Case Study'), ('Show_Quick_Start_Guide__c', 'Show Quick Start Guide'), ('Show_Brochure__c', 'Show Brochure'), ('Show_Kiwapower_at_a_Glance_video__c', 'Show Kiwapower at a Glance video')], max_length=50, unique=True),
        ),
    ]
