# Generated by Django 3.2 on 2021-10-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0011_alter_staticresources_salesforce_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevent',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
