# Generated by Django 3.2 on 2021-10-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0012_sessionevent_document_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlog',
            old_name='sf_error',
            new_name='error',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='error_type',
            field=models.CharField(default='Salesforce', max_length=20),
        ),
    ]
