# Generated by Django 3.2 on 2021-10-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0013_auto_20211005_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticresources',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
