# Generated by Django 3.2 on 2021-10-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0014_staticresources_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticresources',
            name='file_extension',
        ),
        migrations.RemoveField(
            model_name='staticresources',
            name='salesforce_file_id',
        ),
    ]
