# Generated by Django 3.2 on 2021-10-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0015_auto_20211006_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticresources',
            name='s3_file_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
