# Generated by Django 3.2 on 2021-10-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0016_alter_staticresources_s3_file_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticresources',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
