# Generated by Django 3.2 on 2021-04-18 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('label_es', models.CharField(max_length=255, null=True)),
                ('label_en', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('guid', models.CharField(max_length=255, unique=True)),
                ('question', models.CharField(max_length=255)),
                ('question_es', models.CharField(max_length=255, null=True)),
                ('question_en', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=255)),
                ('answer_es', models.CharField(max_length=255, null=True)),
                ('answer_en', models.CharField(max_length=255, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celery.section')),
            ],
        ),
    ]
