# Generated by Django 3.2 on 2021-04-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='guid',
        ),
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
