# Generated by Django 3.2 on 2021-04-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery', '0002_auto_20210419_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='answer_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='question_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='question_es',
            field=models.TextField(null=True),
        ),
    ]
