# Generated by Django 3.2 on 2021-04-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celery', '0003_auto_20210419_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('id',)},
        ),
    ]
